# Generated by Django 4.2.5 on 2023-09-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_publicacion_fav_delete_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='fav',
            field=models.IntegerField(default=0),
        ),
    ]
