# Generated by Django 4.2.5 on 2023-09-19 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_publicacion_fav'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='respuesta_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='myapp.publicacion'),
        ),
    ]
